###################################
#                                 #
#   AuthTools                     #
#                                 #
#   Author: Pavlyi                #
#   Website: http://pavlyi.eu     #
#                                 #
###################################

connection:
    # What type of connection do you want to use?
    # Valid: YAML, SQLITE, MYSQL, MONGODB
    type: YAML

    yaml:
        # YAML file name
        fileName: playerData.yml

    mysql:
        # MySQL host address
        hostname: localhost
        # MySQL port
        port: 3306
        # MySQL database
        database: database
        # MySQL username
        username: username
        # MySQL password
        password: password
    
    sqlite:
        # SQLite file name
        fileName: sqlite.db
    
    mongodb:
        # MongoDB cluster
        cluster: cluster
        # MongoDB database
        database: database
        # MongoDB username
        username: username
        # MongoDB password
        password: password

settings:
    # Should we hook into AuthMe?
    hookIntoAuthMe: false
    # Should we hook into nLogin?
    hookIntoNLogin: false
    # Enable actions only when requested by API?
    actionsOnlyWithAPI: false
    # Should we hook with BungeeCord?
    bungeeCord: false
    # Send player to this BungeeCord server after register/login
    sendPlayerTo: ''
    # Enter here your server name to show when players scan QR Code
    serverName: "Minecraft Server"

    restrictions:
        # Allowed commands to do even when not logged in
        allowedCommands:
        - "2fa recover"
        # After how many seconds should players who fail to login or register be kicked?
        # Set to 0 to disable.
        timeout: 30
        # When this setting is enabled, so that players can't be kicked
        # due to "Logged in from another Location"
        forceSingleSession: true
        # Should players be kicked on wrong 2fa code?
        kickOnWrong2FAcode: false
        # Should players when they join get teleported to spawn
        teleportUnAuthedToSpawn: false
        # Can unregistered players walk around?
        allowMovement: false
        # How far can players walk?
        # Set to 0 for unlimited radius
        allowedMovementRadius: 100
    
    titleAnnouncement:
        title:
            # Enables the title
            enable: true
            # Makes a fade in for title
            fadeIn: 20
            # Makes a fade out for title
            fadeOut: 20
            
            # Enable if you want title in register
            useInRegister: true
            # Enable if you want title in login
            useInLogin: true
        
        subtitle:
            # Enables the title
            enable: true
            # Makes a fade in for title
            fadeIn: 20
            # Makes a fade out for title
            fadeOut: 20
            
            # Enable if you want title in register
            useInRegister: true
            # Enable if you want title in login
            useInLogin: true
        
        actionbar:
            # Enables the title
            enable: true
            
            # Enable if you want title in register
            useInRegister: true
            # Enable if you want title in login
            useInLogin: true
        
        register:
            title: ""
            subtitle: ""
            actionbar: "&cRegister &f- Enter &csecret key &finto &capp &for scan the &cQR Code&f!"
        
        login:
            title: "&c&lLogin"
            subtitle: ""
            actionbar: "&fEnter &cverification code &ffrom &cAuthenticator app&f!"